version: "3.7"

services:
  postgres:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: postgres

  server:
    build: "server"
    ports:
      - "7070-7074:7070"
    environment:
      PROJECT_IDS: project_1
    volumes:
      - "./server:/app"
    init: true
    depends_on:
      - postgres

  frontend:
    build: "frontend"
    ports:
      - "7777:3000"
    volumes:
      - "./frontend:/app"
    command: "yarn dev"

  example_python_repo:
    build: "examples/python_repo"
    volumes:
      - "./examples/python_repo:/app"
      - "./clients/python:/packages"
    environment:
      PROJECT: project_1
      HOST: server:7070
      MODULE: app.repo
      VERSION: 1
    init: true
    depends_on:
      - server

  example_wikipedia:
    build: "examples/wikipedia"
    volumes:
      - "./examples/wikipedia:/app"
      - "./clients/python:/packages"
    environment:
      PROJECT: project_1
      HOST: server:7070
      MODULE: wikipedia.repo
      VERSION: 1
    init: true
    depends_on:
      - server
