version: "3.7"

services:
  postgres:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: postgres

  server:
    build: "server"
    ports:
      - "7070:7070"
    environment:
      PROJECT_IDS: project_1
    volumes:
      - "./server:/app"
    init: true
    depends_on:
      - postgres

  frontend:
    build: "frontend"
    ports:
      - "7777:7777"
    volumes:
      - "./frontend:/app"
    command: "yarn dev"

networks:
  default:
    name: coflux
