version: "3.7"

services:
  repo:
    build: "."
    volumes:
      - ".:/app"
      - "../../clients/python:/packages"
    environment:
      PROJECT: project_1
      ENVIRONMENT: dev/two
      HOST: host.docker.internal:7070
      MODULE: wikipedia.repo
      VERSION: 1
    init: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
