on:
  push:
    # paths: [server/**]
    # branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_push:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.16

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: version
        run: |
          MIX_VERSION=$(mix eval "IO.inspect Mix.Project.config[:version]" | grep -oP '\"\K[^\"]+')
          echo "version=$MIX_VERSION" >> "$GITHUB_OUTPUT"

      - name: Check pushed
        id: pushed
        env:
          TAG: ${{ steps.version.outputs.version }}
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.TAG }} || echo "Image not found"
          echo "pushed=$(if [ $? -eq 0 ]; then echo "false"; else echo "true"; fi)" >> "$GITHUB_OUTPUT"

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,enable=true,value=${{ env.RELEASE_VERSION }}
            type=raw,enable=true,value=latest

      - name: Build/push image
        uses: docker/build-push-action@v5
        with:
          context: server
          push: ${{ steps.pushed.outputs.pushed == 'false' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Release
        if: steps.pushed.outputs.pushed == 'false'
        env:
          VERSION: ${{ steps.version.outputs.version }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create clients/python/$VERSION \
            --title "Server ($VERSION)"
